version: '3.8'

services:
    composer:
        image: composer:2.3.5
        user: ${UID}:${GID}
        volumes:
            - .:/project
            - ${COMPOSER_CACHE_PATH}:/tmp
        working_dir: /project
        entrypoint: composer

    server:
        image: johnnysaymon/php:8.1-arp-1.0
        user: ${UID}:${GID}
        ports:
            - "8000:80"
        volumes:
            - .:/project
            - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
        working_dir: /project
        depends_on:
            - db

    npm:
        image: node:16.15.0-alpine3.15
        user: ${UID}:${GID}
        volumes:
            - .:/project
            - ${NPM_CACHE_PATH}:/.npm
        working_dir: /project
        entrypoint: npm

    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}

